on:
  push:
jobs:
  list-change-stack:
    runs-on: ubuntu-latest
    name: list cfn stack change set
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1-node16 # v1-node16 gets rid of the node12 deprecation warning
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-1
      - name: describe change set
        id: describe-change-set
        uses: ./
        with:
          stack_name: omochi
          template_body: after.cf.yml
      - name: echo output
        run: echo "Result was ${{ steps.describe-change-set.outputs.result }}"
      - name: archive change set
        uses: actions/upload-artifact@v1
        with:
          name: change-set-archive
          path: ${{ steps.describe-change-set.outputs.result_file_path }}

