on:
  pull_request:
    branches:
      - master
    types: opened
jobs:
  list-change-stack:
    runs-on: ubuntu-latest
    name: list cfn stack change set
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: describe change set
        id: describe-change-set
        uses: ./
        with:
          stack_name: omochi
          template_body: after.cf.yml
      - name: echo output
        run: echo "Result was ${{ steps.describe-change-set.outputs.result }}"
